# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\x1a\x1bgoogle/protobuf/empty.proto\"O\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05senha\x18\x04 \x01(\t\x12\x0c\n\x04tipo\x18\x05 \x01(\t\"5\n\x0f\x43\x61\x64\x61stroRequest\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario\"$\n\x10\x43\x61\x64\x61stroResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\",\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\t\"V\n\rLoginResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\"\n\x07usuario\x18\x03 \x01(\x0b\x32\x11.usuarios.Usuario\"=\n\x16ListarUsuariosResponse\x12#\n\x08usuarios\x18\x01 \x03(\x0b\x32\x11.usuarios.Usuario2\xe1\x01\n\x0eGestaoUsuarios\x12I\n\x10\x43\x61\x64\x61strarUsuario\x12\x19.usuarios.CadastroRequest\x1a\x1a.usuarios.CadastroResponse\x12\x38\n\x05Login\x12\x16.usuarios.LoginRequest\x1a\x17.usuarios.LoginResponse\x12J\n\x0eListarUsuarios\x12\x16.google.protobuf.Empty\x1a .usuarios.ListarUsuariosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=57
  _globals['_USUARIO']._serialized_end=136
  _globals['_CADASTROREQUEST']._serialized_start=138
  _globals['_CADASTROREQUEST']._serialized_end=191
  _globals['_CADASTRORESPONSE']._serialized_start=193
  _globals['_CADASTRORESPONSE']._serialized_end=229
  _globals['_LOGINREQUEST']._serialized_start=231
  _globals['_LOGINREQUEST']._serialized_end=275
  _globals['_LOGINRESPONSE']._serialized_start=277
  _globals['_LOGINRESPONSE']._serialized_end=363
  _globals['_LISTARUSUARIOSRESPONSE']._serialized_start=365
  _globals['_LISTARUSUARIOSRESPONSE']._serialized_end=426
  _globals['_GESTAOUSUARIOS']._serialized_start=429
  _globals['_GESTAOUSUARIOS']._serialized_end=654
# @@protoc_insertion_point(module_scope)
