# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import usuarios_pb2 as usuarios__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usuarios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GestaoUsuariosStub(object):
    """Serviço gRPC para gestão de utilizadores:
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CadastrarUsuario = channel.unary_unary(
                '/usuarios.GestaoUsuarios/CadastrarUsuario',
                request_serializer=usuarios__pb2.CadastroRequest.SerializeToString,
                response_deserializer=usuarios__pb2.CadastroResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/usuarios.GestaoUsuarios/Login',
                request_serializer=usuarios__pb2.LoginRequest.SerializeToString,
                response_deserializer=usuarios__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.ListarUsuarios = channel.unary_unary(
                '/usuarios.GestaoUsuarios/ListarUsuarios',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=usuarios__pb2.ListarUsuariosResponse.FromString,
                _registered_method=True)


class GestaoUsuariosServicer(object):
    """Serviço gRPC para gestão de utilizadores:
    """

    def CadastrarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestaoUsuariosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CadastrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastrarUsuario,
                    request_deserializer=usuarios__pb2.CadastroRequest.FromString,
                    response_serializer=usuarios__pb2.CadastroResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=usuarios__pb2.LoginRequest.FromString,
                    response_serializer=usuarios__pb2.LoginResponse.SerializeToString,
            ),
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=usuarios__pb2.ListarUsuariosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuarios.GestaoUsuarios', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuarios.GestaoUsuarios', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GestaoUsuarios(object):
    """Serviço gRPC para gestão de utilizadores:
    """

    @staticmethod
    def CadastrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.GestaoUsuarios/CadastrarUsuario',
            usuarios__pb2.CadastroRequest.SerializeToString,
            usuarios__pb2.CadastroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.GestaoUsuarios/Login',
            usuarios__pb2.LoginRequest.SerializeToString,
            usuarios__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.GestaoUsuarios/ListarUsuarios',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            usuarios__pb2.ListarUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
